### ISSUE TITLE
Use custom standard with exceptions in phpcs.xml

### ISSUE THREAD

**Issue by ironchicken** [squizlabs/PHP_CodeSniffer#1403]
I'm trying to use the Symfony2-coding-standard but with some exceptions in my phpcs.xml. I have the following:
```
<?xml version="1.0" encoding="utf-8" ?>
<ruleset name="My Project">
  <description>My Project</description>
  <file>./src</file>
  <file>./spec</file>
  <rule ref="/path/to/Symfony2-coding-standard/Symfony2">
    <exclude ref="Symfony2.Sniffs.Commenting.ClassCommentSniff" />
    <exclude ref="Symfony2.Sniffs.Commenting.FunctionCommentSniff" />
  </rule>
</ruleset>
```
But I get this error:
```
$ phpcs --report=checkstyle --standard=/path/to/phpcs.xml --stdin-path=/path/to/Some.php < /path/to/Some.php
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "" does not exist' in /usr/share/php/PHP/CodeSniffer.php:1144
Stack trace:
#0 /usr/share/php/PHP/CodeSniffer.php(783): PHP_CodeSniffer->_expandRulesetReference(NULL, '/home/richardle...', 1)
#1 /usr/share/php/PHP/CodeSniffer.php(561): PHP_CodeSniffer->processRuleset('/home/richardle...')
#2 /usr/share/php/PHP/CodeSniffer/CLI.php(870): PHP_CodeSniffer->initStandard(Array, Array)
#3 /usr/share/php/PHP/CodeSniffer/CLI.php(106): PHP_CodeSniffer_CLI->process()
#4 /usr/bin/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /usr/share/php/PHP/CodeSniffer.php on line 1144
```
Am I doing this the right way? I've tried a couple of different `@ref` values including absolute and relative file paths, and without the `Symfony2` suffix.

**Comment by jrfnl** [comment]
@ironchicken You need to use `name` instead of `ref` for the exclusions, like `<exclude name="....">`

See the [wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) for more detailed examples.

**Comment by ironchicken** [comment]
@jrfnl Great, thank you! I have to admit, I did actually look at that document but I somehow managed to type in the wrong thing anyway.

**Comment by jrfnl** [comment]
@ironchicken Happens to the best of us. Glad it works now.
