### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BonBonSlick** [squizlabs/PHP_CodeSniffer#2098]
```
Writing lock file
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
PHP CodeSniffer Config installed_paths set to ../../doctrine/,../../phpstan/,../../doctrine/coding-standard/lib/,../../slevomat/coding-standard/
> composer dump-autoload
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
#0 /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
#1 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(236): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin))
#3 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(76) in /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118

Fatal error: Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
#0 /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
#1 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(236): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin))
#3 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 /var/www/sitenamne/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(76) in /var/www/sitenamne/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118

```

**Comment by gsherwood** [comment]
Closing as this error is not coming from PHPCS itself so I can't do anything to fix it.
