### ISSUE TITLE
Undefined index: scope_condition in FunctionSpacingSniff.php

### ISSUE THREAD

**Issue by morozov** [squizlabs/PHP_CodeSniffer#2852]
Unfortunately, I don't know how to reproduce this issue with the OOTB standards, but here's the minimal required setup:
```sh
cat > composer.json << 'EOF'
{
    "require-dev": {
        "doctrine/coding-standard": "^7.0.2"
    }
}
EOF

cat > phpcs.xml.dist << 'EOF'
<?xml version="1.0"?>
<ruleset>
    <rule ref="Doctrine"/>
</ruleset>
EOF

cat > PhpCodeSnifferFailure.php << 'EOF'
<?php

class PhpCodeSnifferFailure
{
    function fn1()
    {
        while (true) {
            if (true) {
                continue;
            } // if
            if (true) {
            }
        }
    }

    function fn2()
    {
    }
}
EOF

composer install

vendor/bin/phpcbf --version
# PHP_CodeSniffer version 3.5.4 (stable) by Squiz (http://www.squiz.net)

vendor/bin/phpcbf PhpCodeSnifferFailure.php
```

The run results in the following error:
```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_condition in vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php on line 274 in vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php(274): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', 'vendor/s...', 274, Array)
#1 vendor/squizlabs/php_codesniffer/src/Files/File.php(496): PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\FunctionSpacingSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 89)
#2 vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(49): PHP_CodeSniffer\Fixer->fixFile()
#5 vendor/squizlabs in vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

I’m filing it here because the stack trace doesn’t contain any non-squizlabs/php_codesniffer resources.

**Comment by jrfnl** [comment]
Similar to #2851, the problem is caused by the `SlevomatCodingStandard.ControlStructures.EarlyExit` sniff introducing parse errors during fixing.

**Comment by morozov** [comment]
Thank you for the explanation, @jrfnl. Let me check if https://github.com/slevomat/coding-standard/commit/bc3d492f3bb67177e390ae825fcc1986bef111ca fixes this problem.

**Comment by morozov** [comment]
Not reproducible on `dev-master` of the Slevomat Coding Standard (https://github.com/slevomat/coding-standard/commit/a741c09e0b31c7a90e521c0b3c2ed70addb462fd).
