### ISSUE TITLE
[Bug] Fatal error during phpcs check of file with UTF-8 BOM signature.

### ISSUE THREAD

**Issue by lisachenko** [squizlabs/PHP_CodeSniffer#2966]
There is a fatal error for test file with UTF8 BOM signature.

```
Fatal error: Uncaught Error: Call to a member function process() on null in ~/vendor/squizlabs/php_codesniffer/src/Files/File.php:496
Stack trace:
#0 ~/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#1 ~/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#2 ~/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#3 ~/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#4 ~/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#5 {main}
  thrown in ~/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 496
```

Probably, the `\PHP_CodeSniffer\Files\File::cleanUp` method should not clean `$this->ruleset` and `$this->fixer` properties.

**Comment by rodrigoprimo** [comment]
I was not able to reproduce this issue on the latest version of PHPCS (4.x branch). I tested with [`ByteOrderMarkUnitTest.1.inc`](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/2108e8bdff8d6ec6c277fb290403db67f66e435b/src/Standards/Generic/Tests/Files/ByteOrderMarkUnitTest.1.inc). It did not trigger the fatal error described here.

The report doesn't include the PHPCS version, the standard being used, or a sample file to reproduce the problem, which makes it difficult to investigate further.

Given the above, I believe this issue can be closed.

**Comment by jrfnl** [comment]
Fair points @rodrigoprimo. Without more information, this will never be reproducible. Considering nobody else has reported this or added additional information to this issue in nearly six years, I suspect this may have been a glitch and that no further time should be invested in this issue.

If more information is surfaced which would make it reproducible, the issue can be (re)opened in the new repo.
