### ISSUE TITLE
phpcbf: Fatal error in PHP template file.

### ISSUE THREAD

**Issue by mbomb007** [squizlabs/PHP_CodeSniffer#3276]
**Describe the bug**

Fatal PHP error occurs when `phpcbf` is run on a (poorly formatted) PHP template file.

**Code sample**
```php
<?php ?>
<table <?php if ($classes) { print 'class="'. $classes . '" '; } ?><?php print $attributes; ?>>
   <?php if (!empty($title) || !empty($caption)) : ?>
     <caption><?php print $caption . $title; ?></caption>
  <?php endif; ?>
  <?php if (!empty($header)) : ?>
    <thead>
      <tr>
        <?php foreach ($header as $field => $label): ?>
          <th <?php if ($header_classes[$field]) { print 'class="'. $header_classes[$field] . '" '; } ?> scope="col">
            <?php print $label; ?>
          </th>
        <?php endforeach; ?>
      </tr>
    </thead>
  <?php endif; ?>
  <tbody>
    <?php foreach ($rows as $row_count => $row): ?>
      <tr <?php if ($row_classes[$row_count]) { print 'class="' . implode(' ', $row_classes[$row_count]) .'"';  } ?>>
        <?php foreach ($row as $field => $content): ?>
          <td <?php if ($field_classes[$field][$row_count]) { print 'class="'. $field_classes[$field][$row_count] . '" '; } ?><?php print drupal_attributes($field_attributes[$field][$row_count]); ?>>
            <?php print $content; ?>
          </td>
        <?php endforeach; ?>
      </tr>
      <tr <?php if ($row_classes[$row_count]) { print 'class="details ' . implode(' ', $row_classes[$row_count]) .'"';  } ?>>
          <td colspan="<?php print count($row); ?>">
            <?php print $descriptions[$row_count]; ?>
          </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

```

**Custom ruleset**

Using Drupal Coder's `Drupal` ruleset and sniffs.

Composer:

```
            "name": "drupal/coder",
            "version": "8.3.12",
            "source": {
                "type": "git",
                "url": "https://git.drupalcode.org/project/coder.git",
                "reference": "719ddb16aec2e5da4ce274bf3bf8450caef564d4"
            },
```

`vendor/drupal/coder/coder_sniffer/Drupal`

**To reproduce**
1. Create a file called `test.tpl.php` with the code sample above...
2. Run `vendor/bin/phpcbf -p -n --colors --standard=Drupal test.tpl.php`
3. See error message displayed
```
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: str_repeat(): Second argument has to be greater than or equal to 0 in /var/www/html/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/WhiteSpace/ScopeClosingBraceSniff.php on line 185 in /var/www/html/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 [internal function]: PHP_CodeSniffer\Runner->handleErrors(2, 'str_repeat(): S...', '/var/www/html/v...', 185, Array)
#1 /var/www/html/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/WhiteSpace/ScopeClosingBraceSniff.php(185): str_repeat(' ', -1)
#2 /var/www/html/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): Drupal\Sniffs\WhiteSpace\ScopeClosingBraceSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 15)
#3 /var/www/html/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#4 /var/www/html/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#5 /var/www/html/vendor/squizlabs/php_codesniffer/ in /var/www/html/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

**Expected behavior**

**Versions (please complete the following information):**
 - OS: Windows 10 version 2004, using WSL2, run from inside an Ubuntu 20 Docker container
 - PHP: 7.4.16
 - PHPCS: 3.5.8
 - Standard: Drupal

**Additional context**

`phpcs --config-set testVersion 7.4-`

**Comment by mbomb007** [comment]
Nevermind, this should probably go on that repo instead...

**Comment by mbomb007** [comment]
Someone should check. I can't find the other repo for Drupal/Coder

**Comment by mbomb007** [comment]
Found it. Issue: https://www.drupal.org/project/coder/issues/3204177

Can close if the issue is known not to be this project.

**Comment by jrfnl** [comment]
@mbomb007 Yup, this looks like an issue in the `Drupal.WhiteSpace.ScopeClosingBrace` sniff, so should be reported there.
