### ISSUE TITLE
gitstaged filter not working when called through npm husky precommit hook

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#3412]
**Describe the bug**
In my project, I'm using [husky](https://www.npmjs.com/package/husky) to run my pre-commit hooks. In `package.json` I have 

```json
...
"scripts": {
		"__eslintTheme": "eslint src/**/*.js",
		"__stylelintTheme": "stylelint src/**/*.scss",
		"lintStyle": "npm run __stylelintTheme",
		"lintJs": "npm run __eslintTheme",
		"lint": "npm run lintJs && npm run lintStyle && composer standards:check -- --filter=gitstaged",
...
},
"husky": {
	"hooks": {
		"pre-commit": "npm run lint"
	}
}
```

So it triggers any time I do a commit. In my `composer.json` I have these scripts

```json
	"scripts": {
		"analyze": "@php ./vendor/bin/phpstan analyze",
		"standards:check": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcs",
		"standards:fix": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcbf"
	},
```

When I run my commit, all the npm hooks run ok, but the phpcs script fails with

```bash
 @php ./vendor/squizlabs/php_codesniffer/bin/phpcs '--filter=gitstaged'
PHP Fatal error:  Uncaught Error: Class '\PHP_CodeSniffer\Filters\gitstaged' not found in /home/dzoljom/Sites/Project/project-name/wp-content/themes/project-name/vendor/squizlabs/php_codesniffer/src/Files/FileList.php:83
Stack trace:
#0 /home/dzoljom/Sites/Project/project-name/wp-content/themes/project-name/vendor/squizlabs/php_codesniffer/src/Runner.php(382): PHP_CodeSniffer\Files\FileList->__construct()
#1 /home/dzoljom/Sites/Project/project-name/wp-content/themes/project-name/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#2 /home/dzoljom/Sites/Project/project-name/wp-content/themes/project-name/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#3 {main}
  thrown in /home/dzoljom/Sites/Project/project-name/wp-content/themes/project-name/vendor/squizlabs/php_codesniffer/src/Files/FileList.php on line 83
```

When I remove the filter, the script runs fine, but over the entire codebase, not just the committed files.

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset name="Eightshift Boilerplate ruleset">
	<description>Ruleset for the Eightshift Boilerplate.</description>

	<rule ref="Eightshift" />

	<exclude-pattern>*/tests/*</exclude-pattern>
	<exclude-pattern>*/vendor/*</exclude-pattern>
	<exclude-pattern>*/public/*</exclude-pattern>
	<exclude-pattern>*/node_modules/*</exclude-pattern>
	<exclude-pattern>*/storybook/*</exclude-pattern>

	<!-- Additional arguments. -->
	<arg value="sp"/>
	<arg name="basepath" value="."/>
	<arg name="parallel" value="8"/>
	<arg name="extensions" value="php"/>

	<file>.</file>

	<!-- Check for PHP cross-version compatibility. -->
	<config name="testVersion" value="7.2-"/>
	<rule ref="PHPCompatibilityWP"/>

	<config name="minimum_supported_wp_version" value="5.3"/>

	<exclude-pattern>/src/CompiledContainer\.php</exclude-pattern>

</ruleset>
```

**Expected behavior**
PHP_CS should run with the gitstaged filter.

**Versions (please complete the following information):**
 - OS: Windows 10, using WSL2 with Ubuntu 20.04
 - PHP: 7.4.20
 - PHPCS:  3.5.8
 - Standard: Eightshift (custom)

**Comment by jrfnl** [comment]
@dingo-d While Windows is case-insensitive, Linux is not. I think your issue will be fixed if you use `--filter=GitStaged` instead 😀

**Comment by dingo-d** [comment]
Thanks for the tip, I'll give it a go 👍🏼

**Comment by dingo-d** [comment]
Ok, so setting it to `GitStaged` fixed throwing of the PHP errors, but I don't get any error reported, and when I run `composer standards:check` I get the error in the staged file (I introduced it intentionally).

I'll try to investigate what happens when I run one vs the other command with some additional flags.

**Comment by jrfnl** [comment]
@dingo-d I would suspect this is to do with WSL, so would be good if you could check whether your colleagues are getting this issue.

IIRC from previous reports, the PHP native file system functions don't all support WSL well enough. 

Also see #2965 and #3388.

**Comment by dingo-d** [comment]
I'll poke this around since I have a Mac available and a Win PC that I can use, so I'll try to see what is happening, and report back  👍🏼

**Comment by jrfnl** [comment]
@dingo-d I've created PR #3428 to address a similar issue. That PR _may_ solve your issue as well. Would you be able to test this and leave feedback on the PR ?

**Comment by dingo-d** [comment]
I've added the changes from the patch, but I'm still not getting an error when using the `GitStaged` filter

<img width="1110" alt="test" src="https://user-images.githubusercontent.com/8638515/132171947-e6bd195d-d37f-4057-b47a-c6dd05dbe0c5.png">

**Comment by jrfnl** [comment]
Hmm... darn... Looking at the code in the `GitStaged` class, I suspect the use of `Util\Common::realpath()` may be problematic.

Might be something we could debug together ?

**Comment by dingo-d** [comment]
Sure, just say when 😄
