### ISSUE TITLE
TypeError: sequence item 0: expected str instance, list found

### ISSUE THREAD

**Issue by demavend** [squizlabs/PHP_CodeSniffer#734]
The result with running PHP Code Sniffer:
```shell
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 649, in run
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 465, in run
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 421, in execute
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 424, in parse_report
  File "phpcs in /Users/lo/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 150, in shell_out
TypeError: sequence item 0: expected str instance, list found
```

My settings:
1. OS X v10.11
2. Sublime Text 3 Build 3083
3. I have installed all tools that required [sublime phpcs official website](http://benmatselby.github.io/sublime-phpcs/).
```plain
installed:
  fabpot/php-cs-fixer          v1.10  A tool to automatically fix PHP code style
  pdepend/pdepend              2.2.1  Official version of pdepend to be handl...
  phpmd/phpmd                  2.3.2  PHPMD is a spin-off project of PHP Depe...
  sebastian/diff               1.3.0  Diff implementation
  squizlabs/php_codesniffer    2.3.4  PHP_CodeSniffer tokenizes PHP, JavaScri...
  symfony/config               v2.7.5 Symfony Config Component
  symfony/console              v2.7.5 Symfony Console Component
  symfony/dependency-injection v2.7.5 Symfony DependencyInjection Component
  symfony/event-dispatcher     v2.7.5 Symfony EventDispatcher Component
  symfony/filesystem           v2.7.5 Symfony Filesystem Component
  symfony/finder               v2.7.5 Symfony Finder Component
  symfony/process              v2.7.5 Symfony Process Component
  symfony/stopwatch            v2.7.5 Symfony Stopwatch Component
```
4. All tools are set executable_path: scheck, phpcs, phpmd, phpcbf, php_cs_fixer, phpcs_php_path

Below is the php code when I test with PHP Code Sniffer:
```php
<?php
echo 'a';
?>
```

I don't believe this result.

**Comment by gsherwood** [comment]
This project doesn't have anything to do with the Sublime plugin and I am unable to replicate any errors using the command line version of PHPCS and the code you have provided.

Are you sure this error is coming from PHPCS itself, or is it coming from a problem in the Sublime plugin? Can you run PHPCS directly over the file on the command line and see any errors?

**Comment by demavend** [comment]
I've tried to run PHPCS directly on the command line:
```shell
lo:scripts lo$ ./phpcs ~/Sites/hello/hello.php

FILE: /Users/lo/Sites/hello/hello.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 2 | ERROR | Missing file doc comment
----------------------------------------------------------------------

Time: 26ms; Memory: 3Mb
```
It works.
So, my error is with Sublime plugin.

**Comment by aik099** [comment]
@demavend , you can close the issue then.

**Comment by demavend** [comment]
Oh, man. I'm wrong with repo.
I am really sorry.
